[package]
name = "voice-input-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"
voice-input-core = { path = "../voice-input-core" }
voice-input-recorder-cpal = { path = "../voice-input-recorder-cpal" }
voice-input-sinks = { path = "../voice-input-sinks" }
voice-input-transcriber-whisper = { path = "../voice-input-transcriber-whisper" }
